apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: rentomojo
  labels:
    app.kubernetes.io/name: client
    app.kubernetes.io/part-of: rentomojo
spec:
  selector:
    app: rentomojo-client
  ports:
    - name: http
      port: 80
      targetPort: 5173
      protocol: TCP
  type: ClusterIP
